apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: basic-banking system
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: basic-banking system
          image: anushashashidhar/projectt:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: basic-banking system
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
    nodePort: 31110
